version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-platinum:6.2.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ELASTIC_PASSWORD=elastic123"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana-x-pack:6.2.0
    container_name: kibana
    environment:
      SERVER_HOST: "0.0.0.0"
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      ELASTICSEARCH_USERNAME: "elastic"
      ELASTICSEARCH_PASSWORD: "elastic123"
      XPACK_MONITORING_ENABLED: "true"
      XPACK_MONIITORING_HISTORY_DURATION: "1d"
      #This is needed as the stats we collected the monitoring data without containers
      XPACK_MONITORING_KIBANA_COLLECTION_ENABLED: "false"
    ports:
      - 5601:5601
    networks:
      - esnet

volumes:
  esdata1:
    driver: local

networks:
  esnet:
